version: '3.8'
services:
  neo4j:
    image: neo4j:5.11
    environment:
      - NEO4J_AUTH=neo4j/letmein123
    ports:
      - "7474:7474" # Browser
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
